---
apiVersion: v1
kind: Service
metadata:
  name: pg
  namespace: database
  labels:
    app: database
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: pg
    port: 5432
  selector:
    app: database
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pg
  namespace: database
  labels:
    app: database
spec:
  serviceName: pg
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: postgres
        image: POSTGRES
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5432
          name: pg
        env:
        - name: PGDATA
          value: "/var/lib/postgresql/data/pgdata"
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
        - name: config
          mountPath: /docker-entrypoint-initdb.d/sandbox.sql
          subPath: sandbox.sql
        resources:
          limits:
            cpu: 250m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 512Mi
      volumes:
      - name: config
        configMap:
          name: config-database
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1G
