BEGIN;
CREATE ROLE user1 WITH LOGIN ENCRYPTED PASSWORD 'password_user1';
CREATE ROLE user2 WITH LOGIN ENCRYPTED PASSWORD 'password_user2';
COMMIT;

CREATE DATABASE sandbox;
\c sandbox

BEGIN;
CREATE TABLE test(value TEXT);
COMMIT;
